### ISSUE TITLE
Issues with generating builder from an object in another namespace

### ISSUE THREAD

**Issue by powerdude** [StefH/FluentBuilder#36] opened 2022-06-18 20:34 UTC
this doesn't seem to work or generate any errors:

```csharp
namespace namespace1
{
    using System.Diagnostics;

    using FluentBuilder;

   [AutoGenerateBuilder(typeof(MyModel))]
   public partial class MyModelBuilder
    {
    }

    public record MyModel
    {
        /// <summary>
        ///     Gets or sets the name.
        /// </summary>
        public string Name { get; set; } = "Unknown";
    }
}

namespace namespace2
{
    using FluentBuilder;

    using namespace1;

   // doesn't work
    [AutoGenerateBuilder(typeof(MyModel))]
    public partial class MyModelBuilder2
    {
    }
}
```

**Comment by StefH** [comment] 2022-06-19 20:15
This problem is probably caused by the way your c# file is organized.
Did you try another layout ? (See this project / unit tests for examples)

**Comment by powerdude** [comment] 2022-06-19 20:48
this is to merely illustrate the problem.  Put both namespaces in a separate file and the problem is still there.  the compiler doesn't care how things are grouped.

**Comment by StefH** [comment] 2022-06-19 21:25
I think when you use ` [AutoGenerateBuilder(typeof(namespace1.MyModel))]`, it does work?

**Comment by powerdude** [comment] 2022-06-19 21:34
no because it wouldn't matter.  the code above compiles since the class is resolved because of the `using namespace1`.  the source generator doesn't parse the text of the file, but uses the syntax tree of the source and can resolve the class.  the problem is the builder you generate when the attribute is on a partial builder class uses the namespace of the targeted type, not the namespace of the builder.  Here's the resulting code:

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using RedDragon.BeastMode.Tests.FluentBuilder;
using namespace1;

namespace namespace1 // this should be namespace2
{
    public partial class MyModelBuilder : Builder<namespace1.MyModel>
    {
        private bool _nameIsSet;
        private Lazy<string> _name = new Lazy<string>(() => string.Empty);
        public MyModelBuilder WithName(string value) => WithName(() => value);
        public MyModelBuilder WithName(Func<string> func)
        {
            _name = new Lazy<string>(func);
            _nameIsSet = true;
            return this;
        }
        public MyModelBuilder WithoutName()
        {
            WithName(() => string.Empty);
            _nameIsSet = false;
            return this;
        }


        public override MyModel Build(bool useObjectInitializer = true)
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<MyModel>(() =>
                {
                    if (useObjectInitializer)
                    {
                        return new MyModel
                        {
                            Name = _name.Value
                        };
                    }

                    var instance = new MyModel();
                    if (_nameIsSet) { instance.Name = _name.Value; }
                    return instance;
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        public static MyModel Default() => new MyModel();

    }
}

```

**Comment by StefH** [comment] 2022-06-20 20:26
It fixed in https://github.com/StefH/FluentBuilder/pull/37

Can you take a look?

**Comment by powerdude** [comment] 2022-06-20 21:53
Looks like it worked.  thanks!

**Closed** 2022-06-21 06:14 UTC
